name: ci

on:
  push:
  pull_request:

jobs:
  build:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - linux-clang

        configuration:
          - Debug
          - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: linux-clang
            os: ubuntu-latest
            compiler: clang

    steps:
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.5
      with:
        boost_version: 1.83.0
        cache: "true"
        link: static

    - name: Setup Boost Env
      run: |
        echo "BOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}" >> ${GITHUB_ENV}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure (${{ matrix.configuration }})
      run: |
        env
        cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: |
        env
        cmake --build build --parallel --config ${{ matrix.configuration }}
