name: ci

on:
  push:
  pull_request:

jobs:
  build:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - linux-clang

        configuration:
          - Debug
          - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: linux-clang
            os: ubuntu-latest
            compiler: clang

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build --parallel --config ${{ matrix.configuration }}
