name: ci

on:
  push:
  pull_request:

jobs:
  build:

    name: ${{ matrix.toolchain }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc

        configuration:
          - Debug
          - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

    steps:
    - name: Download and extract Boost
      run: |
        mkdir -p $HOME/boost
        cd $HOME/boost
        curl -LO https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.gz
        tar xzf boost_1_84_0.tar.gz

    - name: Build and install Boost
      run: |
        cd $HOME/boost/boost_1_84_0
        set +e
        ./bootstrap.sh --with-libraries=all --prefix=$HOME/boost/install
        ./b2 cxxflags="-fPIC -std=c++11" --with=all --prefix=$HOME/boost/install install
        set -e
        echo "CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$HOME/boost/install" >> ${GITHUB_ENV}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure (${{ matrix.configuration }})
      run: |
        cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: |
        cmake --build build --parallel --config ${{ matrix.configuration }}
